site_name: LLM System and Engineering
site_url: https://wzbxpy.github.io/LLM-System-and-Engineering
theme:
  name: material
extra_css:
  - style.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
